package Example;


/**
* Example/_ModesImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from example.idl
* Wednesday, October 9, 2013 1:11:20 PM IST
*/

public abstract class _ModesImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements Example.Modes, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _ModesImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("operation", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Example/Modes/operation
       {
         String inArg = in.read_string ();
         org.omg.CORBA.IntHolder outArg = new org.omg.CORBA.IntHolder ();
         org.omg.CORBA.IntHolder inoutArg = new org.omg.CORBA.IntHolder ();
         inoutArg.value = in.read_long ();
         int $result = (int)0;
         $result = this.operation (inArg, outArg, inoutArg);
         out = $rh.createReply();
         out.write_long ($result);
         out.write_long (outArg.value);
         out.write_long (inoutArg.value);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Example/Modes:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _ModesImplBase
