package Example;


/**
* Example/ModesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from example.idl
* Wednesday, October 9, 2013 1:11:20 PM IST
*/

public interface ModesOperations 
{
  int operation (String inArg, org.omg.CORBA.IntHolder outArg, org.omg.CORBA.IntHolder inoutArg);
} // interface ModesOperations
