package Example;


/**
* Example/Modes.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from example.idl
* Wednesday, October 9, 2013 1:11:20 PM IST
*/

public interface Modes extends ModesOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Modes
